diff -urN phc-winner-argon2-20171227.org/Makefile phc-winner-argon2-20171227/Makefile
--- phc-winner-argon2-20171227.org/Makefile	2017-12-27 20:56:31.000000000 +0100
+++ phc-winner-argon2-20171227/Makefile	2018-05-14 20:24:50.018634693 +0200
@@ -30,7 +30,7 @@
 SRC_GENKAT = src/genkat.c
 OBJ = $(SRC:.c=.o)
 
-CFLAGS += -std=c89 -O3 -Wall -g -Iinclude -Isrc
+CFLAGS += -std=c89 -Wall -g -Iinclude -Isrc
 
 ifeq ($(NO_THREADS), 1)
 CFLAGS += -DARGON2_NO_THREADS
@@ -42,7 +42,7 @@
 				-Wextra -Wno-type-limits -Werror -coverage -DTEST_LARGE_RAM
 
 OPTTARGET ?= native
-OPTTEST := $(shell $(CC) -Iinclude -Isrc -march=$(OPTTARGET) src/opt.c -c \
+OPTTEST := $(shell $(CC) -Iinclude -Isrc src/opt.c -c \
 			-o /dev/null 2>/dev/null; echo $$?)
 # Detect compatible platform
 ifneq ($(OPTTEST), 0)
@@ -50,7 +50,7 @@
 	SRC += src/ref.c
 else
 $(info Building with optimizations for $(OPTTARGET))
-	CFLAGS += -march=$(OPTTARGET)
+	
 	SRC += src/opt.c
 endif
 
@@ -99,6 +99,7 @@
 endif
 
 LIB_SH := lib$(LIB_NAME).$(LIB_EXT)
+LIB_SH_VERSION := $(LIB_SH).0
 LIB_ST := lib$(LIB_NAME).a
 
 ifdef LINKED_LIB_EXT
@@ -180,6 +181,10 @@
 endif
 	$(INSTALL) -d $(INST_BINARY)
 	$(INSTALL) $(RUN) $(INST_BINARY)
+	# rename library to match SONAME
+	mv $(INST_LIBRARY)/$(LIB_SH) $(INST_LIBRARY)/$(LIB_SH_VERSION)
+	# keep symlink for development
+	ln -sf $(LIB_SH_VERSION) $(INST_LIBRARY)/$(LIB_SH)
 
 uninstall:
 	cd $(INST_INCLUDE) && rm -f $(notdir $(HEADERS))
